DROP TABLE MEMBER;

SELECT * FROM MEMBER;

SELECT * FROM BOARD;

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('오늘 저녁에 하늘마당에서 보실 분', '내가 치킨 쏜다', '명훈쌤');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕', '내가 치킨 쏜다', '아이유');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('ㅎ2', '내가 치킨 쏜다', '제니');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('배고파', '내가 치킨 쏜다', '리사');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('ㅂ2', '내가 치킨 쏜다', '준용쌤');